export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK"
export const SEARCHCTASK = "SEARCHCTASK"
export const UPDATETASKTITLE = "UPDATETASKTITLE"
export const UPDATETASKCOMPLITED = "UPDATETASKCOMPLITED"


